version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=http://localhost:3000/api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"


        