version: '3.8'

services:
  api:
    build: .
    ports:
      - "3500:3500"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/celsia_internet
    depends_on:
      - mongo
    volumes:
      - .:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  mongo:
    image: mongo:5
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  mongo-data: